export const INITIALIZE_TOKEN = "INITIALIZE_TOKEN";
export const SET_PLAYLIST = "SET_PLAYLIST";
export const SET_USERINFO = "SET_USERINFO";
export const SET_INITIALPLAYLIST = "SET_INITIALPLAYLIST";
export const SET_SELECTEDPLAYLIST = "SET_SELECTEDPLAYLIST";
