export const UPDATE_VIDEOS   = "UPDATE_VIDEOS";
export const SEARCHED_VIDEOS = "SEARCHED_VIDEOS";
export const CHANNEL_DETAILS = "CHANNEL_DETAILS";
export const CHANNEL_VIDEOS  = "CHANNEL_VIDEOS";
export const OTHER_CHANNELS  = "OTHER_CHANNELS";


